version: 0.0
os: linux
files:
  - source: s3://umocharacerjar/server/backend-build.zip
    destination: /home/ubuntu/server/backend
    overwrite: yes

permissions:
  - object: /home/ubuntu/server/backend
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
